---
title: "HW 01"
author: "Elizabeth Ladd"
format: 
  html:
    embed-resources: true
toc: true
---

## 0 - Setup

```{r setup}

if (!require("pacman")) 
 install.packages("pacman")
# use this line for installing/loading
pacman::p_load(tidyverse,
               here,
               glue,
               scales,
               ggthemes) 

devtools::install_github("tidyverse/dsbox")


```

## 1 - Road traffic accidents in Edinburgh

```{r Plot 1}

# set theme for ggplot2
ggplot2::theme_set(ggplot2::theme_minimal(base_size = 14))

# set width of code output
options(width = 65)

# set figure parameters for knitr
knitr::opts_chunk$set(
  fig.width = 7,        # 7" width
  fig.asp = 0.618,      # the golden ratio
  fig.retina = 3,       # dpi multiplier for displaying HTML output on retina
  fig.align = "center", # center align figures
  dpi = 300             # higher dpi, sharper image
)
#read in accidents data
accidents <- read_csv(here(
  "data" ,"accidents.csv"))

 #creates a "day category" column in the accidents data 
accidents <- accidents|>
 mutate(
   day_cat = case_when(
     day_of_week %in% c("Saturday", "Sunday") ~ "Weekend", 
     TRUE ~ "Weekday")
 ) 
accidents |> glimpse() 

accidents |> 
  count(day_cat, time, severity) |>
ggplot(aes(time, fill=severity, color=severity))+
  geom_density(alpha= 0.1) +
  facet_wrap(~day_cat) +
  labs(
    x = "Time of Day",
    y = "Density",
    title = "Number of accidents throughout the day",
    subtitle = "By day of the week and severity",
  )+
  scale_color_colorblind()+
  theme_minimal(base_size = 14)+
  theme(
    legend.position = "right",

  )

```

## 2 - NYC marathon winners

```{r label-me-2}

```

## 3 - US counties

## 4 - Rental apartments in SF

## 5 - Napoleon’s march.
